Ensure the final job status is correct if either ruff check failed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,11 +31,21 @@ jobs:
           python3 -m pip install ruff
 
       - name: ruff check
+        idf: ruff-check
         continue-on-error: true
         run: |
           python3 -m ruff check --output-format=github
 
       - name: ruff format --check
+        id: ruff-format
         continue-on-error: true
         run: |
           python3 -m ruff format --check
+
+      # if ruff check or ruff format failed, the whole job should fail (but both should be checked)
+      - name: Output job status
+        if: steps.ruff-check.outcome == "failure" || steps.ruff-format.outcome == "failure"
+        run: | 
+          echo "ruff check or ruff format --check failed"
+          exit 1
+        
